config-version: 2

name: "dbt_101"
version: "1.0.0"

profile: "dbt_101_profile"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["data-tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  "dbt_date:time_zone": "Australia/Sydney"

seeds:
  dbt_101:
    jaffle_data:
      +schema: raw
      +enabled: "{{ var('load_source_data', false) }}"

models:
  jaffle_shop:
    staging:
      +materialized: view
    marts:
      +materialized: table
